Routing
systemseed/falcon pull request #100
Opened 2019-07-23 16:25 UTC by PavelBulat

2019-07-24 09:05 UTC, kalabro requested changes

2019-07-24 09:05 UTC, kalabro commented on .env.default
> +SETTINGS_NAME='falcon_default'
Can we rename `SETTINGS_NAME` to  `APPLICATION_NAME` and `STATIC_MAX_AGE` to `STATIC_CACHE_MAX_AGE`?

2019-07-24 09:05 UTC, kalabro commented on falcon/modules/features/falcon_feature_demo/config/install/menu_link_config.menu_link_config.create_a_new_article.yml
> +  node_type: 4b868b94-2d37-40f5-965a-f8922c65ba4c
Can you check if it works? I think it should be `news`.

2019-07-24 09:05 UTC, kalabro commented on falcon/modules/features/falcon_feature_demo/config/install/menu_link_config.menu_link_config.create_a_new_page.yml
> +  node_type: a85c1597-ffcc-4912-9da8-497f85210f5a
the same as with news link

2019-07-24 09:05 UTC, kalabro commented on falconjs/packages/falcon/package.json
> +    "express-basic-auth": "^1.1.6",
everything below `express-basic-auth` should be moved to dependencies.

2019-07-24 09:05 UTC, kalabro commented on falconjs/packages/falcon/routes/clearCache.js
> +  if (parsedUrl.pathname === '/_cacheclear') {
Move url to default/server.js (this middleware should not care about url).

2019-07-24 09:05 UTC, kalabro commented on falconjs/packages/falcon/routes/frontendOnlyRoutes.js
> +const pathToRegexp = require('path-to-regexp');
Rename routes/ to routing/ folder.

2019-07-24 09:05 UTC, kalabro commented on falconjs/packages/falcon/routes/getPageContent.js
> +async function getPageContent(requestedURL, res = null, request = null) {
Rename to getEntityContent

2019-07-24 09:05 UTC, kalabro commented on falconjs/packages/falcon/routes/getPageContent.js
> +    ? res.normalizedRequestPath : parsedUrl.pathname;
Move all custom res/req properties under falcon, i.e. `res.falcon.normalizedRequestPath`

2019-07-24 09:05 UTC, kalabro commented on falconjs/packages/falcon/routes/globalSettings.js
> +const getHomepageLink = (settings, isRaw = false) => {
Move away from server-side code (it looks like util or transform).

2019-07-24 09:05 UTC, kalabro commented on falconjs/packages/falcon/routes/globalSettings.js
> +
why new line?

2019-07-24 09:05 UTC, kalabro commented on falconjs/packages/falcon/routes/globalSettings.js
> +          res.settings = settingsFromCache;
res.falcon.settings

2019-07-24 09:05 UTC, kalabro commented on falconjs/packages/falcon/routes/globalSettings.js
> +function homePageInSettings(req, res, next) {
handleHomepageRequest

2019-07-28 13:24 UTC, PavelBulat commented on .env.default
> +SETTINGS_NAME='falcon_default'
Done.

2019-07-28 13:29 UTC, PavelBulat commented on falcon/modules/features/falcon_feature_demo/config/install/menu_link_config.menu_link_config.create_a_new_article.yml
> +  node_type: 4b868b94-2d37-40f5-965a-f8922c65ba4c
It doesn't work. Reverted.

2019-07-28 13:29 UTC, PavelBulat commented on falcon/modules/features/falcon_feature_demo/config/install/menu_link_config.menu_link_config.create_a_new_page.yml
> +  node_type: a85c1597-ffcc-4912-9da8-497f85210f5a
Reverted.

2019-07-28 13:31 UTC, PavelBulat commented on falconjs/packages/falcon/package.json
> +    "express-basic-auth": "^1.1.6",
Probably express-basic-auth should be moved to dependancies too. How do you think @kalabro ?

2019-07-28 13:31 UTC, PavelBulat commented on falconjs/packages/falcon/routes/clearCache.js
> +  if (parsedUrl.pathname === '/_cacheclear') {
Done.

2019-07-28 13:31 UTC, PavelBulat commented on falconjs/packages/falcon/routes/frontendOnlyRoutes.js
> +const pathToRegexp = require('path-to-regexp');
Done.

2019-07-28 13:32 UTC, PavelBulat commented on falconjs/packages/falcon/routes/getPageContent.js
> +async function getPageContent(requestedURL, res = null, request = null) {
Done.

2019-07-28 13:32 UTC, PavelBulat commented on falconjs/packages/falcon/routes/getPageContent.js
> +    ? res.normalizedRequestPath : parsedUrl.pathname;
Done.

2019-07-28 13:32 UTC, PavelBulat commented on falconjs/packages/falcon/routes/globalSettings.js
> +const getHomepageLink = (settings, isRaw = false) => {
Moved to utils as new file.

2019-07-28 13:33 UTC, PavelBulat commented on falconjs/packages/falcon/routes/globalSettings.js
> +
Removed.

2019-07-28 13:33 UTC, PavelBulat commented on falconjs/packages/falcon/routes/globalSettings.js
> +          res.settings = settingsFromCache;
Done.

2019-07-28 13:33 UTC, PavelBulat commented on falconjs/packages/falcon/routes/globalSettings.js
> +function homePageInSettings(req, res, next) {
Done.

2019-08-02 10:44 UTC, cneuro commented on falconjs/packages/falcon/routes/frontendOnlyRoutes.js
> +function frontendOnlyRoutes(nextApp, routes) {
We seem to have a mix of named functions with ES6 function syntax (e.g. line 61) alongside these anonymous declarations in several files. Wouldn't it better if we made all function declarations consistent with ES6 syntax in the `const` style?

2019-08-02 10:54 UTC, cneuro commented on falconjs/packages/falcon/routes/frontendOnlyRoutes.js
> +function frontendOnlyRoutes(nextApp, routes) {
An example with `async`: 
```
const funcName = async (param) => {};
```

2019-08-13 08:34 UTC, merged