Auto-determine OS and change .env
systemseed/falcon pull request #44
Opened 2019-01-10 16:56 UTC by PavelBulat

2019-01-10 17:13 UTC, spleshka submitted a review, later dismissed

2019-01-10 17:13 UTC, spleshka commented on Makefile
> +configuring_env:
Rename it to something like `prepare\:images`

2019-01-10 17:13 UTC, spleshka commented on Makefile
> +	@if [ $(OS_NAME) = "Linux" ]; then \
Please use makefile's if/else clause.

2019-01-11 07:33 UTC, duozersk submitted a review, later dismissed

2019-01-11 07:33 UTC, duozersk commented on Makefile
> +		echo "${cyan}${bold}$(PROJECT_NAME): Defined OS LINUX. Change PHP_TAG for docker image in environment${reset}" \
We have a defined function for messages like this, see `$(call message,...)` examples in this file.

2019-01-11 07:33 UTC, duozersk commented on Makefile
> +        sed -i -E '/PHP_TAG.+-dev-macos-/s/^/# /g' \.env; \
Smth is wrong with indentations here (indents are not the same for the lines in one block) - check where you use tabs and where the blank symbols. Tabs are essential for Makefile syntax (first tab in a line tells make that it is an instruction to execute / shell command), but once you started the shell command and use the multiline syntax with '\' at the end of lines - then all the indents of the next line are going into this shell command.

2019-01-11 07:33 UTC, duozersk commented on Makefile
> +prepare: | configuring_env | up
There should not be two `|` symbols in this line, only the first one makes sense.

2019-01-11 07:58 UTC, spleshka commented on Makefile
> +        $(shell sed -i '/PHP_TAG/s/^# //g' \.env)
Need comments what this is doing.

2019-01-11 07:59 UTC, spleshka commented on Makefile
> +# Define OS system.
You don't define it, you save the current OS system value into a varaible.

2019-01-11 08:24 UTC, duozersk requested changes
Looks good to me! Please just add a new command name into the `.PHONY` list at the top.

2019-01-11 08:24 UTC, duozersk commented on Makefile
> +prepare\:images:
This new command name should be added at the top in the `.PHONY` commands list.

2019-01-11 08:30 UTC, PavelBulat commented on Makefile
> +prepare\:images:
Thanks, it is fixed now.

2019-01-11 09:27 UTC, duozersk approved these changes

2019-01-11 09:27 UTC, merged