Ecards
systemseed/falcon pull request #66
Opened 2019-02-27 08:10 UTC by PavelBulat

2019-03-06 15:18 UTC, ikorgik requested changes

2019-03-06 15:18 UTC, ikorgik commented on .docker/docker-compose.override.default.yml
> +#    image: pavelbulat/xdebug_codeception
Currently it conflicts with Kate's changes, can you please check with her?

2019-03-06 15:18 UTC, ikorgik commented on composer.json
> +        "Added new hook_alter": "https://www.drupal.org/files/issues/2019-02-22/commerce_decoupled_checkout-added_hook_alter-3033373-5.patch"
Do you know when this patch can be committed?

2019-03-06 15:18 UTC, ikorgik commented on modules/custom/falcon_gift_ecards/falcon_gift_ecards.module
> +        Drupal::logger('falcon_gift_ecards')->alert($e->getMessage());
I would define more meaningful alert message and attached $e->getMessage() additionally. 
e.g: `->alert("Can't create an event entity. Error: " . $e->getMessage());`

2019-03-06 15:18 UTC, ikorgik commented on modules/custom/falcon_gift_ecards/src/EventSubscriber/FalconOrderCompletedSubscriber.php
> +              $this->mailSender->send($card);
I would recommend to wrap this part with try-catch

2019-03-06 15:18 UTC, ikorgik commented on modules/custom/falcon_gift_ecards/falcon_gift_ecards.module
> +  }
Do we need 'break' at the end of case?

2019-03-06 15:18 UTC, ikorgik commented on modules/custom/falcon_gift_ecards/src/MailSender.php
> +    $to = $ecardItem->get('field_recipient_email')->value;
I would recommend to wrap this function with try-catch

2019-03-06 15:18 UTC, ikorgik commented on modules/custom/falcon_gift_ecards/src/MailSenderInterface.php
> +interface MailSenderInterface {
Do we need an empty interface file here at all?

2019-03-06 15:21 UTC, PavelBulat commented on composer.json
> +        "Added new hook_alter": "https://www.drupal.org/files/issues/2019-02-22/commerce_decoupled_checkout-added_hook_alter-3033373-5.patch"
@spleshka When you know when this patch can be committed? =))

2019-03-07 07:45 UTC, PavelBulat commented on .docker/docker-compose.override.default.yml
> +#    image: pavelbulat/xdebug_codeception
Merged

2019-03-07 07:46 UTC, PavelBulat commented on modules/custom/falcon_gift_ecards/falcon_gift_ecards.module
> +        Drupal::logger('falcon_gift_ecards')->alert($e->getMessage());
The message added.

2019-03-07 07:46 UTC, PavelBulat commented on modules/custom/falcon_gift_ecards/src/EventSubscriber/FalconOrderCompletedSubscriber.php
> +              $this->mailSender->send($card);
Done.

2019-03-07 07:48 UTC, PavelBulat commented on modules/custom/falcon_gift_ecards/falcon_gift_ecards.module
> +  }
The 'break'  added.

2019-03-07 07:48 UTC, PavelBulat commented on modules/custom/falcon_gift_ecards/src/MailSender.php
> +    $to = $ecardItem->get('field_recipient_email')->value;
Done.

2019-03-07 07:48 UTC, PavelBulat commented on modules/custom/falcon_gift_ecards/src/MailSenderInterface.php
> +interface MailSenderInterface {
Deleted.

2019-03-07 09:38 UTC, ikorgik approved these changes

2019-03-07 09:39 UTC, merged